### ISSUE TITLE
What is this error?

### ISSUE THREAD

**Issue by 0n1dev** [aaa4xu/pubg-lobby-proxy#3]
ubg-lobby-proxy-master\src\AssetsServer.js:47
             {type: PubgRequest.TYPES.NORMAL, flags: null, arguments: []},
             ^
SyntaxError: Unexpected token {
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Comment by aaa4xu** [comment]
What version of node.js do you use?

**Comment by 0n1dev** [comment]
install v7.10.0

**Comment by 0n1dev** [comment]
![ee](https://user-images.githubusercontent.com/10239804/33532748-b440a366-d8df-11e7-9bf0-70705c562fcb.png)
what happen?

**Comment by aaa4xu** [comment]
I dont see sslstrip server in logs. Do you use old version of pubg proxy?
