### ISSUE TITLE
Game server closed connection

### ISSUE THREAD

**Issue by myserywork** [aaa4xu/pubg-lobby-proxy#8]
I am getting this while trying to use the proxy 

Game server closed connection
Game client closed connection

wss://prod-live-entry.playbattlegrounds.com/userproxy?provider=steam&ticket=&playerNetId=7656119809046
3543&cc=BR&timezoneOffset=-3&clientGameVersion=3.7.33&fullClientGameVersion=3.7.33.33

**Comment by busheezy** [comment]
Anyone know the new way? The game connects fine with the host file changed so I feel like the endpoints have changed.

**Comment by aaa4xu** [comment]
Looks like they update dns name for backend. Plz check last revision

**Comment by busheezy** [comment]
You're the best. I'll check it out. Thanks!

**Comment by busheezy** [comment]
Did you have success with the last revision? I'm getting "Servers are too busy, please try again later." when I try routing it through your proxy.

**Comment by busheezy** [comment]
I just realized, in my own connection code I've been using prod-live-entry since at least March 13th. Something else has changed.

**Comment by aaa4xu** [comment]
Pushed new revision. This version works for me currently.

**Comment by busheezy** [comment]
https://i.imgur.com/521ELAA.jpg Any ideas?

**Comment by aaa4xu** [comment]
Do you restart game? Seems like you dont load frontend page from pubg proxy

**Comment by busheezy** [comment]
Yes, sorry. I restarted the proxy and pressed reconnect to make the error easy to see. Here is a complete log from a non-launched game.

```
C:\Users\ryan9\Desktop\pubg-lobby-proxy>yarn start
yarn run v1.6.0
$ npm run start:prod

> pubg-proxy@1.0.0 start:prod C:\Users\ryan9\Desktop\pubg-lobby-proxy
> node index.js

Websocket server started at http://localhost:8001
SSLStrip server started at http://localhost:443
Bluehole assets server ip:  52.85.112.7, 52.85.112.14, 52.85.112.17, 52.85.112.36, 52.85.112.45, 52.85.112.50, 52.85.112.93, 52.85.112.181
Assets server started at http://localhost:80
Frontend url: https://prod-live-front.playbattlegrounds.com/app/pc-1.7-2018.05.02-2768/index-steam.pc-1.7-2018.05.02-2768.html
Asset: /app/pc-1.7-2018.05.02-2768/coherent/coherent.mock.style.css
Asset: /app/pc-1.7-2018.05.02-2768/assets/css/swiper.min.css
Asset: /app/pc-1.7-2018.05.02-2768/coherent/coherent.js
Asset: /app/pc-1.7-2018.05.02-2768/styles.2d7113888206ae1eeadb.bundle.css
Asset: /app/pc-1.7-2018.05.02-2768/assets/js/jquery-3.2.1.min.js
Asset: /app/pc-1.7-2018.05.02-2768/coherent/coherent.mock.js
Asset: /app/pc-1.7-2018.05.02-2768/coherent/mock.entry.js
Asset: /app/pc-1.7-2018.05.02-2768/inline.bundle.js
Asset: /app/pc-1.7-2018.05.02-2768/polyfills.bundle.js
Asset: /app/pc-1.7-2018.05.02-2768/styles.2d7113888206ae1eeadb.bundle.css
Asset: /app/pc-1.7-2018.05.02-2768/vendor.bundle.js
Asset: /app/pc-1.7-2018.05.02-2768/main.bundle.js
Asset: /app/pc-1.7-2018.05.02-2768/splash-img.bf7c6744a799c6d394bb.jpg
Asset: /app/pc-1.7-2018.05.02-2768/pubg-logo.b0f4b57878e6ddfcdb04.png
Connection from steamId= 76561197972581267
Asset: /app/pc-1.7-2018.05.02-2768/splash-img.bf7c6744a799c6d394bb.jpg
PUBG Client error: { Error: socket hang up
    at createHangUpError (_http_client.js:335:15)
    at TLSSocket.socketOnEnd (_http_client.js:428:23)
    at TLSSocket.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19) code: 'ECONNRESET' }
Game server closed connection
Game client closed connection
Asset: /app/pc-1.7-2018.05.02-2768/create-bg.59515cddaa34145ba0c7.jpg
Asset: /app/pc-1.7-2018.05.02-2768/logo.4f9a9d5cf6aba6f16a65.png
```

**Comment by aaa4xu** [comment]
Try "restart lobby" several times. I got your problem once, but cant reproduce it.

Update: But, found another problem. Ok, this require more time than expected.

**Comment by busheezy** [comment]
I tried connecting about 30 times, without any luck. I tried another IP without any luck. Do you think it is worth trying another account? Feel free to add me on discord. BuSheeZy#6487.  
  
Let me know if I can help.

**Comment by whitesunset** [comment]
:hankey:
   :hankey::hankey:
:hankey::hankey::hankey:

**Comment by aaa4xu** [comment]
@myserywork Its pubg problem, not a proxy

**Comment by myserywork** [comment]
Any solution?

**Comment by busheezy** [comment]
The latest revision should work.

**Comment by lemeshovich** [comment]
im getting same error like @busheezy had
```
PUBG Client error: { Error: socket hang up
    at createHangUpError (_http_client.js:335:15)
    at TLSSocket.socketOnEnd (_http_client.js:428:23)
    at TLSSocket.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19) code: 'ECONNRESET' }
Game server closed connection
Game client closed connection
```
do we have any solutions to fix that?

**Comment by lemeshovich** [comment]
getting that with
```
127.0.0.1 prod-live-front.playbattlegrounds.com
127.0.0.1 pctest-live-front.playbattlegrounds.com
127.0.0.1 prod-live-entry.playbattlegrounds.com
127.0.0.1 pctest-live-entry.playbattlegrounds.com
```
in hosts
when leaving only 
```
127.0.0.1 prod-live-front.playbattlegrounds.com
127.0.0.1 pctest-live-front.playbattlegrounds.com
```
getting that when trying to follow http://127.0.0.1/debug.html
https://imgur.com/a/qGxsZLA
